version: "3.5"

services:
  solar-api:
    image: solar-api:release
    restart: always
    build:
      context: .
      dockerfile: API/API/Dockerfile
    environment:
      - ASPNETCORE_ConnectionStrings__Database=server=mysql;port=4600;database=database;uid=root;pwd=hT4sR8Kja!*h
    networks:
      - solar-network
    ports:
      - 9080:80
      - 9443:443
  solar-app:
    image: solar-app:release
    restart: always
    stdin_open: true
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - 9001:80
      - 9002:443
    networks:
      - solar-network
  noti-worker:
    image: noti-worker:release
    restart: always
    build:
      context: .
      dockerfile: NotiWorker/NotiWorker/Dockerfile
    networks:
      - solar-network

networks:
  solar-network:
    external:
      name: solar-network
