/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { ServiceClientOptions } from "@azure/ms-rest-js";
import * as msRest from "@azure/ms-rest-js";

/**
 * An interface representing ClientDto.
 */
export interface ClientDto {
  id?: string;
}

/**
 * An interface representing RepresentativeDto.
 */
export interface RepresentativeDto {
  id?: string;
}

/**
 * An interface representing APIOptions.
 */
export interface APIOptions extends ServiceClientOptions {
  baseUri?: string;
}

/**
 * Optional Parameters.
 */
export interface APIGetByIdOptionalParams extends msRest.RequestOptionsBase {
  id?: string;
}

/**
 * Optional Parameters.
 */
export interface APIGetById1OptionalParams extends msRest.RequestOptionsBase {
  id?: string;
}

/**
 * Contains response data for the getById operation.
 */
export type GetByIdResponse = ClientDto & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ClientDto;
    };
};

/**
 * Contains response data for the getById1 operation.
 */
export type GetById1Response = RepresentativeDto & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: RepresentativeDto;
    };
};
