/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import * as msRest from "@azure/ms-rest-js";


export const ClientDto: msRest.CompositeMapper = {
  serializedName: "ClientDto",
  type: {
    name: "Composite",
    className: "ClientDto",
    modelProperties: {
      id: {
        serializedName: "id",
        type: {
          name: "Uuid"
        }
      }
    }
  }
};

export const RepresentativeDto: msRest.CompositeMapper = {
  serializedName: "RepresentativeDto",
  type: {
    name: "Composite",
    className: "RepresentativeDto",
    modelProperties: {
      id: {
        serializedName: "id",
        type: {
          name: "Uuid"
        }
      }
    }
  }
};
